# Generated by Django 5.1.5 on 2025-01-20 17:08

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='Kapacita')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Obrázek pokoje')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Jméno zákazníka')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email zákazníka')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Telefon zákazníka')),
                ('check_in_date', models.DateField(verbose_name='Datum příjezdu')),
                ('check_out_date', models.DateField(verbose_name='Datum odjezdu')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=20, verbose_name='Stav platby')),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID platby Stripe')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Pokoj')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Obrázek')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Popis obrázku')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='Pokoj')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Název pokoje')),
                ('description', models.TextField(verbose_name='Popis pokoje')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rooms.room')),
            ],
            options={
                'verbose_name': 'room Translation',
                'db_table': 'rooms_room_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
